image: node:lts-alpine

before_script:
  - node -v

variables:
  CLI_VERSION: 12.2.0
  HEROKU_APP: mega-cat
  HEROKU_API_KEY: 1aac7cb9-5ec6-429d-86e1-eb0f8bf01ea3

stages:
  - lint
  - test
  - build
  - deploy

build:
  stage: build
  image: trion/ng-cli:${CLI_VERSION}
  before_script:
    - npm ci
  script:
    - ng build --configuration=bkcn-production
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
  tags:
    - docker

test:karma:
  stage: test
  image: trion/ng-cli-karma
  before_script:
    - npm ci
  allow_failure: false
  script:
    - ng test  --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - coverage/
    reports:
      junit: [reports/*.xml, karma_html/index.html]
  tags:
    - docker

test:lint:
  stage: lint
  before_script:
    - npm ci
  allow_failure: false
  script:
    - npm run lint
  tags:
    - docker

todo:e2e:
  stage: test
  # image: trion/ng-cli:${CLI_VERSION}
  allow_failure: false
  script:
    - echo "Implement"

heroku-deploy:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - Achievement